name: Actions

on:
  push:
    branches:
    - main
    - 'test-gha-2.*'
    tags:
    - 'test-gha-2.*'
  pull_request:
    branches:
    - main
    - 'test-gha-2.*'

jobs:

  scope:
    name: get scope
    runs-on: ubuntu-22.04
    steps:
    - name: Generate scope
      id: scope
      run: |
        scope="unknown"
        if [ ${{ github.event_name }} = pull_request ]; then
          # pr (main or enterprise-2.XX)
          scope=${{github.base_ref}}
        elif [ ${{ github.event_name }} = push ]; then
          github_ref=${{github.ref}}
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            # merge (main or enterprise-2.XX)
            scope=${github_ref#refs/heads/}
          elif [[ ${{ github.ref }} == refs/tags/enterprise-2.* ]]; then
            # tag (enterprise-2.XX)
            github_tag=${github_ref#refs/tags/}
            scope=$(echo "$github_tag" | cut -d '.' -f 1,2)
          elif [[ ${{ github.ref }} == refs/tags/preview-* ]]; then
            # tag (main)
            scope=main
          fi
        fi
        echo "scope=$scope" >> "$GITHUB_OUTPUT"
        echo Scope: $scope

    - name: Generate channel
      id: channel
      run: |
        channel=enterprise
        if [ ${{ steps.scope.outputs.scope }} = main ]; then
          channel=preview
        fi
        echo "channel=$channel" >> "$GITHUB_OUTPUT"
        echo Channel: $channel

  dump:
    name: dump info
    runs-on: ubuntu-22.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump Job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
