name: Actions

on:
  push:
    branches:
    - main
    - 'test-gha-2.*'
    tags:
    - 'test-gha-2.*'
  pull_request:
    branches:
    - main
    - 'test-gha-2.*'

jobs:

  dump:
    name: dump info
    runs-on: ubuntu-22.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump Job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
